name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag federicocorchia/web_server
    - name: Push the image to DockerHub
      run: docker login -u federicocorchia -p ${{ secrets.DOCKER_TOKEN }} && docker push federicocorchia/web_server
